### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by eugene2candy** [gy0p4k/newtab#3]
https://github.com/gy0p4k/newtab/blob/5b6b00219a9e79c8a8d48a918e75e702a5fe231e/index.html#L9

better to use built-in font since google api not working in every country
```css
* {
  font-family: "PingFang SC";
}
```
